version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped    
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: admin
      PGDATA: /data/postgres      
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - database-network      

  redis:
    container_name: redis_container  
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
  redis_data:

networks: 
  database-network:
    driver: bridge  
