spring:
  application:
    name: desafio
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      password: macecar

management:
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  retry:
    retry-aspect-order: 2
    instances:
      notificacaoRetry:
        max-attempts: 3
        wait-duration: 4s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.RestClientException
        ignore-exceptions:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      notificacaoCircuitBreaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60
        failure-rate-threshold: 60


